# Generated by Django 5.0.4 on 2024-05-30 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=70, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=70, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=60, verbose_name='Correo electrónico')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('celular', models.CharField(max_length=30, null=True, verbose_name='Celular')),
                ('telefono_fijo', models.CharField(max_length=30, null=True, verbose_name='Teléfono fijo')),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
