# Generated by Django 5.0.4 on 2024-05-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
