# Generated by Django 5.0.4 on 2024-05-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='activo',
            new_name='active',
        ),
    ]
