# Generated by Django 5.0.4 on 2024-05-23 00:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_activo_producto_descripcion_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
    ]
