# Generated by Django 5.0.4 on 2024-05-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_codigo_alter_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('orden', models.PositiveSmallIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.producto')),
            ],
            options={
                'db_table': 'imagen_producto',
            },
        ),
    ]
