# Generated by Django 5.0.4 on 2024-05-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_bitacora_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
